### ISSUE TITLE
Portlet is temporarily unavailable

### ISSUE THREAD

**Issue by mistvan** [nonblocking/liferay-angularjs-portlet#4]
Hi there,

can you advice on following error? I tried to deploy your portlet onto liferay 6.1.1 on my windows machine. After I tried add portlet on page I got portlet unavailable message and in console this error:
`08:26:16,309 ERROR [http-bio-8280-exec-16][render_portlet_jsp:154] java.io.FileNotFoundException: The requested resource (/liferay-angularjs-portlet/WEB-INF/servlet/view/portal/index) is not available
	at org.apache.catalina.servlets.DefaultServlet.serveResource(DefaultServlet.java:776)
	at org.apache.catalina.servlets.DefaultServlet.doGet(DefaultServlet.java:411)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)`

Appreciate any help, thanks!

**Comment by mistvan** [comment]
Undeploy and deploy portlet again to tomcat resolved issue.
